/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Upgradeable__factory>;
    getContractFactory(
      name: "ERC721Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Upgradeable__factory>;
    getContractFactory(
      name: "IERC721MetadataUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721MetadataUpgradeable__factory>;
    getContractFactory(
      name: "IERC721ReceiverUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721ReceiverUpgradeable__factory>;
    getContractFactory(
      name: "IERC721Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Upgradeable__factory>;
    getContractFactory(
      name: "ERC165Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165Upgradeable__factory>;
    getContractFactory(
      name: "IERC165Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165Upgradeable__factory>;
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeacon__factory>;
    getContractFactory(
      name: "ERC1967Upgrade",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Upgrade__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Pausable__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "IAdmin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAdmin__factory>;
    getContractFactory(
      name: "IPauser",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPauser__factory>;
    getContractFactory(
      name: "Authenticator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Authenticator__factory>;
    getContractFactory(
      name: "Admin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Admin__factory>;
    getContractFactory(
      name: "CollectionSiteAdminAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CollectionSiteAdminAuthority__factory>;
    getContractFactory(
      name: "CollectionSiteCreatorAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CollectionSiteCreatorAuthority__factory>;
    getContractFactory(
      name: "CollectionSiteDestroyerAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CollectionSiteDestroyerAuthority__factory>;
    getContractFactory(
      name: "CollectionSiteRevokerAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CollectionSiteRevokerAuthority__factory>;
    getContractFactory(
      name: "MasterAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MasterAuthority__factory>;
    getContractFactory(
      name: "PauserAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PauserAuthority__factory>;
    getContractFactory(
      name: "Roles",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Roles__factory>;
    getContractFactory(
      name: "TokenBurnerAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenBurnerAuthority__factory>;
    getContractFactory(
      name: "TokenMinterAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenMinterAuthority__factory>;
    getContractFactory(
      name: "TokenOperatorAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenOperatorAuthority__factory>;
    getContractFactory(
      name: "TokenRevokerAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenRevokerAuthority__factory>;
    getContractFactory(
      name: "TokenSenderAuthority",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenSenderAuthority__factory>;
    getContractFactory(
      name: "AuthorityFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AuthorityFactory__factory>;
    getContractFactory(
      name: "ERC20Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Upgradeable__factory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
  }
}
