/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface RolesInterface extends ethers.utils.Interface {
  functions: {
    "COLLECTION_SITE_ADMIN_ROLE()": FunctionFragment;
    "COLLECTION_SITE_CREATOR_ROLE()": FunctionFragment;
    "COLLECTION_SITE_DESTROYER_ROLE()": FunctionFragment;
    "COLLECTION_SITE_REVOKER_ROLE()": FunctionFragment;
    "PAUSER_ROLE()": FunctionFragment;
    "TOKEN_BURNER_ROLE()": FunctionFragment;
    "TOKEN_MINTER_ROLE()": FunctionFragment;
    "TOKEN_OPERATOR_ROLE()": FunctionFragment;
    "TOKEN_REVOKER_ROLE()": FunctionFragment;
    "TOKEN_SENDER_ROLE()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "COLLECTION_SITE_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COLLECTION_SITE_CREATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COLLECTION_SITE_DESTROYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COLLECTION_SITE_REVOKER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_BURNER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_REVOKER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_SENDER_ROLE",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COLLECTION_SITE_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COLLECTION_SITE_CREATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COLLECTION_SITE_DESTROYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COLLECTION_SITE_REVOKER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_BURNER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_REVOKER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_SENDER_ROLE",
    data: BytesLike
  ): Result;

  events: {};
}

export class Roles extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RolesInterface;

  functions: {
    COLLECTION_SITE_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    COLLECTION_SITE_CREATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    COLLECTION_SITE_DESTROYER_ROLE(
      overrides?: CallOverrides
    ): Promise<[string]>;

    COLLECTION_SITE_REVOKER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    TOKEN_BURNER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    TOKEN_MINTER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    TOKEN_OPERATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    TOKEN_REVOKER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    TOKEN_SENDER_ROLE(overrides?: CallOverrides): Promise<[string]>;
  };

  COLLECTION_SITE_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  COLLECTION_SITE_CREATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  COLLECTION_SITE_DESTROYER_ROLE(overrides?: CallOverrides): Promise<string>;

  COLLECTION_SITE_REVOKER_ROLE(overrides?: CallOverrides): Promise<string>;

  PAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

  TOKEN_BURNER_ROLE(overrides?: CallOverrides): Promise<string>;

  TOKEN_MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

  TOKEN_OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  TOKEN_REVOKER_ROLE(overrides?: CallOverrides): Promise<string>;

  TOKEN_SENDER_ROLE(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    COLLECTION_SITE_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    COLLECTION_SITE_CREATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    COLLECTION_SITE_DESTROYER_ROLE(overrides?: CallOverrides): Promise<string>;

    COLLECTION_SITE_REVOKER_ROLE(overrides?: CallOverrides): Promise<string>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

    TOKEN_BURNER_ROLE(overrides?: CallOverrides): Promise<string>;

    TOKEN_MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

    TOKEN_OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    TOKEN_REVOKER_ROLE(overrides?: CallOverrides): Promise<string>;

    TOKEN_SENDER_ROLE(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    COLLECTION_SITE_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    COLLECTION_SITE_CREATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    COLLECTION_SITE_DESTROYER_ROLE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    COLLECTION_SITE_REVOKER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_BURNER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_MINTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_OPERATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_REVOKER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_SENDER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    COLLECTION_SITE_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    COLLECTION_SITE_CREATOR_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    COLLECTION_SITE_DESTROYER_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    COLLECTION_SITE_REVOKER_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TOKEN_BURNER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TOKEN_MINTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TOKEN_OPERATOR_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TOKEN_REVOKER_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TOKEN_SENDER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
